### ISSUE TITLE
Requerimientos para registrar usuario

### ISSUE THREAD

**Issue by Daniel9822** [BrunoSobrino/api#3]
Me preguntaba ¿cuáles son los requerimientos para hacer la funcionalidad de crear y loguear usuarios?

1. ¿En que base de datos se guardara la información o si se usara base de datos?
2. ¿Se usaría algún proveedor para el registro?
3. ¿Se usarán tokens para la autorización?
etc.

Pregunto por qué busque en el readme, y no veo ningún requerimiento, ni tampoco vi issues acerca de esto.

**Comment by BrunoSobrino** [comment]
¡Hola Daniel! El sistema de registro será algo sencillo.

Será una pagina simple de login el cual pedira correo y contraseña, luego les mandará a una pagina donde tendran que confirmar el correo mediante un codigo de verificacion, esto le asignará una apikey al usuario con ciertos limites de uso diario, el que esta llevando a cabo este sistema de login y registro es [@ferhacks](https://github.com/ferhacks) y me comentó que usara una base de datos local en un json. 

![Datos](https://github.com/BrunoSobrino/api/assets/90165013/e97a86cd-a56d-453d-8c64-9ccbb7818c48)

**Comment by Daniel9822** [comment]
ahhhhh perfecto, gracias por avisar

**Comment by BrunoSobrino** [comment]
Gracias por fijarte en mi proyecto 😅, seguimos en contacto por estos medios!

**Comment by Daniel9822** [comment]
😂😂 no hay de que, siempre he usado tu bot y ahora vi este proyecto y quise aportar

**Comment by ferhacks** [comment]
Aqui esta la pull para el sistema de registro y login
#6
